### ISSUE TITLE
작동원리 - 모터부문

### ISSUE THREAD

**Issue by OpusK** [oroca/oroca_rov#2]
여러 동영상 참고 결과
기본적으로는 가라앉거나 기체가 잠긴 상태로 둥둥 떠있는 것으로 보입니다. (기타 참고 동영상 참조)
https://youtu.be/3SJhmbqvvW4?t=1m31s
( 링크 첫 장면에서도 OpenROV 2.7이 물속으로 쑥 들어가버립니다 - 1분31초)

하지만, Trident같은 경우는 둥둥 떠있는거 같기도 하구요..
(OpenROV 의 경우도 둥둥 떠있는 듯하다가 Dive하는 영상이 있습니다)

---

https://youtu.be/CxOoE_3Yr8g?t=2m36s (2분 36초 부분부터)
예전 블루스카이님이 보여주셨던 ROV인데,
이 동영상에서 모터의 움직임이 가장 확실하게 보입니다.
적어도 여기에서는 상단모터가 동작함으로써  ROV가 수면으로 부상합니다.

https://youtu.be/VSK7dIzPw0A?t=1m8s (1분8초부터)
Trident의 경우도 상단모터에 의해 수면위로 더 올라오는거 같습니다.
특히 이녀석의 경우 후진하는 모습이 보이는데..
그런 회로를 구성해서 상하전후의 움직임으로 다양한 움직임을 낼 수 있는 것은 아닌지 생각이 듭니다.

---

Open Source로 하는만큼, 어느정도 작동원리에 대해 이해하고 설정하는게 좋을 거 같아
찾아보았습니다. 그리고 Issues란이니 여기서 의견을 많이 나누었으면 합니다 :)

기타 참고 동영상
https://youtu.be/Vt4XMlSjv0c
    - 이 동영상의 경우, 파이프 안의 기포를 인위적으로 흔들어서 제거해준 뒤 잠수하기 때문에
      바닥에 가라앉은 상태로 시작하는 것일 수도 있습니다.

https://www.youtube.com/watch?v=Zfdg6ZXSQ5Q

**Comment by chcbaram** [comment]
OpenROV의 제어보드의 아두이노 코드중에 아래와 같이 모터 제어부분을 찾아보았습니다. 모터속도를 개별로 제어하는것도 있지만 아래와 같이 크게는 3가지 제어요소를 가지고 있더군요. 
- thro : 추진모터 왼쪽/오른쪽의 속도를 제어함
- yaw : 추진모터 왼쪽/오른쪽의 좌우 속도비를 조정하여 ROV를 좌/우로 회전시킴
- lift : 가운데 모터속도를 제어해서 ROV를 들어올리거나 내림.

우리도 일단 아래와 같은 방식으로 따라해 보면 어떨까 생각됩니다. 

[Thrusters2X1.cpp](https://github.com/OpenROV/openrov-software-arduino/blob/master/OpenROV/Thrusters2X1.cpp)
- Thrusters2X1.cpp 파일의 모터 제어 부분
  - thro명령과 yaw명령
  
  ``` c++
  if (command.cmp("thro") || command.cmp("yaw")){
    if (command.cmp("thro")){
      if (command.args[1]>=-100 && command.args[1]<=100) {
        trg_throttle = command.args[1]/100.0;
      }
    }
  
    if (command.cmp("yaw")) {
        //ignore corrupt data
        if (command.args[1]>=-100 && command.args[1]<=100) { //percent of max turn
          trg_yaw = command.args[1]/100.0;
        }
    }
  
    // The code below spreads the throttle spectrum over the possible range
    // of the motor. Not sure this belongs here or should be placed with
    // deadzon calculation in the motor code.
    if (trg_throttle>=0){
      p = 1500 + (500.0/abs(port_motor.motor_positive_modifer))*trg_throttle;
      s = p;
    } else {
      p = 1500 + (500.0/abs(port_motor.motor_negative_modifer))*trg_throttle;
      s = p;
    }
  
    trg_motor_power = s;
  
    int turn = trg_yaw*250; //max range due to reverse range
    if (trg_throttle >=0){
      int offset = (abs(turn)+trg_motor_power)-2000;
      if (offset < 0) offset = 0;
      p = trg_motor_power+turn-offset;
      s = trg_motor_power-turn-offset;
    } else {
      int offset = 1000-(trg_motor_power-abs(turn));
      if (offset < 0) offset = 0;
      p = trg_motor_power+turn+offset;
      s = trg_motor_power-turn+offset;
    }
  }
  ```
  - lift 명령
  
  ``` c++
  if (command.cmp("lift")){
    if (command.args[1]>=-100 && command.args[1]<=100) {
      trg_lift = command.args[1]/100.0;
      v = 1500 + 500*trg_lift;
    }
  }
  ```
